name: reduceSPI
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov
  - coverage
  - flake8-black
  - flake8-docstrings
  - flake8-import-order
  - numpy>=1.18.1
  - pip
  - pytest
  - pytest-cov
  - pytorch>=1.8.1
  - pip:
    - pre-commit
